[package]
name = "mdrv-gpui-tokio"
version = "0.270.1"
description.workspace = true
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_tokio.rs"
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui_util.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
